sudo: required
services:
  - docker

env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
    - CLOUDSDK_PYTHON=$(pyenv which python) # Set the Python version for gcloud

before_install:
  # Decrypt the service account key
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  
  # Install pyenv to manage Python versions
  - curl https://pyenv.run | bash
  - export PATH="$HOME/.pyenv/bin:$PATH"
  - eval "$(pyenv init --path)"
  - eval "$(pyenv init -)"
  - eval "$(pyenv virtualenv-init -)"

  # Install Python 3.8 and set it as the global version
  - pyenv install 3.8.10
  - pyenv global 3.8.10

  # Install the Google Cloud SDK
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc

  # Update gcloud components and configure gcloud
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project fib-app-k8s
  - gcloud config set compute/zone asia-south1-a
  - gcloud container clusters get-credentials fib-app-cluster
  
  # Log in to Docker and build the Docker image
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t pranshu72001/react-test-k8s -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true pranshu72001/react-test-k8s npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
